### ISSUE TITLE
Push stats on shutdown

### ISSUE THREAD

**Issue by sinnlosername** [Bastian/bStats-Metrics#1]
Hey,

it would be nice if stats can also be pushed on shutdown. As it is only pushed every 30 minutes, there might be no data if the server run only 29 minutes. :/

**Comment by Eyremba** [comment]
Yes, this would be very good!

**Comment by BtoBastian** [comment]
Hey,

Thank you for your suggestion. Sounds like a good idea. :)

**Comment by randombyte-developer** [comment]
The first data was sent 5 minutes after startup. What if the server shuts down at 6 minutes uptime? The important interval of 30 minutes would be violated: https://github.com/BtoBastian/bStats-Metrics/blob/94acfb0e97831d866b9e6a28d442a27e4862d954/bstats-bukkit/src/main/java/org/bstats/Metrics.java#L157

**Comment by BtoBastian** [comment]
Sending more than 1 request every 30 minutes is not such a big deal, the additional requests just get ignored. 
There were lots of people who modified the interval (e.g. 10 minutes etc.) which was completely pointless (besides spamming my backend with more request), that's the reason for the warning.

**Comment by sinnlosername** [comment]
Is this limit per IP or per stats uuid? If it's per ip, it would explain why it only shows 200 players for me, while it is running on two big server networks which got 8k players together. ._.

**Comment by DoNotSpamPls** [comment]
IPs aren't tracked afaik, so the UUID is what bStats identifies with.

**Comment by Tanju42** [comment]
This thread is really old but I solved the problem by adding a Temp file which writes all the stored stats in the file and when the server starts back up it gets the file and loads all in a array

And another think is when bStats trys to send the data and it fails it also keeps the data only when the data was sent succesfully the data gets cleared (ArrayList)

I did it with an ArrayList<String, Integer> where String is the id of the chart and Integer is the value

**Comment by Bastian** [comment]
Besides the package, the bStats Metrics class **must not** be modified in any way without any exception.

**Comment by Bastian** [comment]
I've decided to not implement this feature. I doubt that it would make a noticable difference.
