### ISSUE TITLE
Update versions in include-metrics documentation

### ISSUE THREAD

**Issue by lokka30** [Bastian/bStats-Metrics#101]
In the [include metrics](https://bstats.org/getting-started/include-metrics) documentation, the bStats version is `2.2.1` but the latest is `3.0.0` as of writing this. There may be other outdated versions e.g. maven plugins, but I haven't checked.

**Comment by Bastian** [comment]
Fixed in https://github.com/Bastian/bStats/commit/3c8830c522133bba7addb315290e79c08486f59f
