### ISSUE TITLE
Misprint

### ISSUE THREAD

**Issue by V0rHaM** [Bastian/bstats-metrics#109]
file Metrics.java
![изображение](https://user-images.githubusercontent.com/91176180/197402202-2ad1df9b-162d-4f1e-9eb6-fb971cf92396.png)

**Comment by NoahvdAa** [comment]
That is not a typo, that’s the full method signature

**Comment by V0rHaM** [comment]
And what does 'L' stand for

**Comment by SisaNyza** [comment]
> And what does 'L' stand for

This is used in the JNI (and the JVM internally in general) to indicate a type. Primitives are denoted with a single letter (`Z` for boolean, `I` for int, etc), `[` indicates an array, and `L` is used for a class (terminated by a ;).

**Comment by V0rHaM** [comment]
Thank you for the answer
