### ISSUE TITLE
Will adding an `@SuppressWarnings` annotation violate the Metrics file policy?

### ISSUE THREAD

**Issue by Grass-block** [Bastian/bstats-metrics#125]
So a see this warning when I want to add an `@SuppressWarning` annotation to mute IDEA from giving me warnings of this class.
Does this violate the warnings in the tempate files? 
Or if there's any way to mute IDEA warning check to this file without adding an  `@SuppressWarning` annotation here?

I haven't build this version and release it, so if i need to I will remove these lines. :D

My changes:
![QQ_1722058548268](https://github.com/user-attachments/assets/13cd9c93-7c60-4b15-95ff-cd7a15c11917)

Warnings in file:
![QQ_1722058517050](https://github.com/user-attachments/assets/6f5edb4a-a9f3-4c03-a265-eb1cabc3c221)

**Comment by Bastian** [comment]
> Does this violate the warnings in the tempate files?

Yes, it does. However, you have my approval to suppress these warnings. :)
