### ISSUE TITLE
Add option to check if Metrics is enabled 

### ISSUE THREAD

**Issue by Narimm** [Bastian/bStats-Metrics#23]
We need to be able to check if Metrics is enabled.  

E.g I have a listener I want to enable if the server is using bstats.  If they arent I dont need the listener running as they are not recording the stats anyway

I figured something simple
public boolean enabled;

enabled = config.get... etc

I can PR it if you want?

**Comment by BtoBastian** [comment]
Better late than never: https://github.com/BtoBastian/bStats-Metrics/commit/833281db47c0b1d8b6378c2fe480d4d20dcc7c23
Will be part of version 1.3 (soon™)
