### ISSUE TITLE
Can not delete the chart yet

### ISSUE THREAD

**Issue by montlikadani** [Bastian/bStats-Metrics#35]
I still can not delete the chart at this one.
Reopen #30 
![kep](https://user-images.githubusercontent.com/30026208/41666174-23c548e8-74aa-11e8-9ab0-3a89155b45bb.png)
Project: ~~https://bstats.org/plugin/bukkit/ScoreBoards#update_value~~

**Comment by DoNotSpamPls** [comment]
What happens if you try to rename it, or click the button?

**Comment by montlikadani** [comment]
I've deleted the plugin since I've also been removed from the Spigot page.
