### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by xXSchrandXx** [Bastian/bStats-Metrics#40]
Hi,

I want to use your Metrics for my plugin. I added a simple isEnabled method:
`private YamlConfiguration config;
public boolean isEnabled() {
  return config.getBoolean("enabled");
}`
How shall I state this change from your orginal?

And as you write in your [License](https://github.com/Bastian/bStats-Metrics/blob/master/LICENSE) I have to include your copyright and license.
Where do I find your copyright?
Do I need to implement "your" GNU Lesser General Public License v3.0 too, if I use it on my own plugin?

**Comment by Bastian** [comment]
He,

I don't really care that much about the license and I would most likely not choose this license for bStats again. 
If you want to be on the safe side, I recommend you to just add a comment above your addition, that this is the part you modified.

**Comment by Bastian** [comment]
For your interest:
The new version (1.3) now has an `isEnabled` method by default.
