### ISSUE TITLE
Small fork with opt-out

### ISSUE THREAD

**Issue by randombyte-developer** [Bastian/bStats-Metrics#47]
So is there any chance you could provide an official release for Sponge which uses opt-out instead of opt-in? It is intended for plugins not distributed on Ore.

**Comment by Bastian** [comment]
Sorry, but I don't plan on doing this.
It's already a real pita to maintain 6 different classes (Bukkit, Bungeecord and Sponge; Normal + Lite) and I feel like there won't be a significant amount of people using it to be worth the effort.

**Comment by randombyte-developer** [comment]
Ok
