### ISSUE TITLE
Unknown user registered my plugin

### ISSUE THREAD

**Issue by John000708** [Bastian/bStats-Metrics#48]
Hello there, I recently decided to move my plugins from McStats over to bStats (huge kudos for making such an awesome service!). As the title suggests, I found out that somebody else has already registered my plugin under their own account. 

The plugin can be found [here](https://bstats.org/plugin/bukkit/SlimefunOres) on bStats and [here](https://dev.bukkit.org/projects/slimefunores) on Bukkit. Although not a big deal, I was wondering whether there was a way to transfer the ownership back to me?

Thanks in advance!

**Comment by Bastian** [comment]
Hi, you should now be able to register your plugin again. :)
