### ISSUE TITLE
Firewall settings for bStats

### ISSUE THREAD

**Issue by alfdef1** [Bastian/bStats-Metrics#56]
I am using bStats for my plugins and figured out that on some of my servers i am testing that, bStats isn't reporting statistics.

I have some strict firewall settings for incoming traffic, are there some special ports to be whitelisted for making bStats working?

**Comment by DoNotSpamPls** [comment]
bStats Metrics use HTTP POST requests, so allowing traffic to port 443 should be sufficient.

**Comment by Bastian** [comment]
I assume that his has been resolved. Feel free to open a new issue if there are any problems.
