### ISSUE TITLE
org.bstats:bstats-bukkit:jar:1.2

### ISSUE THREAD

**Issue by baxandrei** [Bastian/bStats-Metrics#59]
org.bstats:bstats-bukkit:jar:1.2: Failed to read artifact descriptor for org.bstats:bstats-bukkit:jar:1.2: Could not transfer artifact org.bstats:bstats-bukkit:pom:1.2 from/to bstats-repo (http://repo.bstats.org/content/repositories/releases/): Failed to transfer http://repo.bstats.org/content/repositories/releases/org/bstats/bstats-bukkit/1.2/bstats-bukkit-1.2.pom. Error code 522, Origin Connection Time-out

**Comment by DoNotSpamPls** [comment]
repo.bstats.org is deprecated, please have a look at the [getting started](https://bstats.org/getting-started) page to add the new repository

**Comment by baxandrei** [comment]
Ty
