### ISSUE TITLE
Could not find a suitable constructor in org.bstats.sponge.Metrics2

### ISSUE THREAD

**Issue by confuser** [Bastian/bStats-Metrics#63]
Receiving a number of reports with the following errors from a variety of plugins which crashes Sponge servers

https://gist.github.com/PulzHF/7392a6f00435a3d54ae5013c34c81142
https://pastebin.com/wdgR9Tdg

Appears to be a conflict between bStat versions with plugins on Sponge?

**Comment by confuser** [comment]
Downgrading to v1.4 on Sponge appears to have resolved this

**Comment by Bastian** [comment]
Thank you for reporting!
I've tested the Sponge bStats class on the latest Sponge version (`spongevanilla-1.12.2-7.1.10.jar`) and there's no error.
Maybe it's some incompatibility with plugins that use an older bStats version. I still have to test this.

**Comment by Mohron** [comment]
I've seen a similar issue when multiple versions of bStats co-exist. This wasn't an issue when you could relocate the package in your own jar.

https://pastebin.com/raw/dibQPwML

**Comment by Bastian** [comment]
I assume that this should no longer happen with the `2.x.x` Metrics classes.
Please comment if someone still encounters this issue in the new Metrics classes and I'll reopen the issue.
