### ISSUE TITLE
Clarify why relocating bstats is not necessarry for bstats-sponge

### ISSUE THREAD

**Issue by Shynixn** [Bastian/bStats-Metrics#64]
* Can you please clarify why I do not have to relocate the bstats package when using Sponge? 
* What happens if someone else shades a different bstats version to the same classpath? 
``org.bstats.sponge``

**Comment by Bastian** [comment]
To be honest, I don't know.
Most of the code for the Sponge Metrics class was rewritten my @mbax in https://github.com/Bastian/bStats-Metrics/pull/38.
My current guess would be, that Sponge has a different class loader per plugin and thus it doesn't matter.
Maybe @mbax can elaborate the reasoning behind it a little bit better.

**Comment by Shynixn** [comment]
Thank you for your reply!

Yes, this would be interesting.

**Comment by Bastian** [comment]
While it's probably technically still not necessary, the new Sponge Metrics classes (`2.x.x`) now require relocation again.
