### ISSUE TITLE
feat: add GitHub used by metric

### ISSUE THREAD

**Issue by T0biii** [Bastian/bStats-Metrics#65]
GitHub introduced a "new" metric, which I find much more relevant than stars or downloads. It shows the number of times a dependency is used by other repositories.
Like: 
![Image of ](https://user-images.githubusercontent.com/103008/58381225-c4911d80-7fba-11e9-9179-1964cc18e963.png)
![Image of ](https://user-images.githubusercontent.com/103008/58381227-c9ee6800-7fba-11e9-907e-9c49e3cdeafa.png)

Copyed from https://github.com/netlify/staticgen/issues/ 507

you can see: https://github.com/T0biii/JoinMusic/network/dependencies is depending on it but it is not Linked to this GitHub Page

**Comment by Bastian** [comment]
I guess GitHub does not properly handle multi-module projects.
![image](https://user-images.githubusercontent.com/5033001/80996347-f2741880-8e3f-11ea-98be-3a93615d4326.png)

I don't think there's anything I can do.

**Comment by T0biii** [comment]
mmh: https://github.blog/changelog/2019-08-15-users-can-now-choose-the-package-displayed-in-used-by/
there should be a option? or Github cant resolce the pom? correctly :(

**Comment by Bastian** [comment]
I cannot find any options

**Comment by T0biii** [comment]
we can close it see: https://github.com/koca2000/NoteBlockAPI/issues/48#issuecomment-637165036
