### ISSUE TITLE
Scoreboard+bStats in plugins

### ISSUE THREAD

**Issue by SorinC244** [Bastian/bStats-Metrics#66]
A "SkyPlex" scoreboard appears on my server. I uninstalled each plugin one by one to see which one it was from, then I removed them all, but the scareboard always remains. In the plugins folder it still appears, always a folder named "bStats".  I need help

**Comment by DoNotSpamPls** [comment]
Vanilla Minecraft also has a scoreboard, which can be edited using the /scoreboard command.
bStats is a metrics service integrated into Paper, you can't remove that folder. However, it is not the cause of your problem.

**Comment by Bastian** [comment]
Like @DoNotSpamPls said, this is not related to bStats. If you still have a bStats folder with no installed plugins, it is generated by your server software (Paper or similar).

**Comment by SorinC244** [comment]
The problem is that there is no command / scoreboard: / The scoreboard appeared after I installed 4 plugins at once without restart and since then it doesn't disappear.

**Comment by DoNotSpamPls** [comment]
Again, this is not a problem caused by bStats. You would be better off asking for help in the [PaperMC Discord](https://discord.gg/papermc)
