### ISSUE TITLE
Any updates on Velocity support?

### ISSUE THREAD

**Issue by STG-Allen** [Bastian/bStats-Metrics#70]
I noticed the issue: #39  and #52 seem to be a bit outdated and was curious as to the progress of Velocity support. If any help is needed I am willing to contribute where possible, but would like to get a better understanding of where the team stands on adding Velocity support.

**Comment by Bastian** [comment]
Seeing that Velocity seems to become more popular, I will look into it soon (probably next month).

**Comment by Bastian** [comment]
Better late then never. bStats now has full support for Velocity plugins! 🎉
