### ISSUE TITLE
Using bstats for Minecraft related standalone programs

### ISSUE THREAD

**Issue by LOOHP** [Bastian/bStats-Metrics#73]
Is there a way I can use bstats to collected from custom Minecraft standalone programs such as custom server implementations?

**Comment by Bastian** [comment]
There's a non-public "Other" category that basically allows you to do anything and is currently only used by a [MC Server Soft](https://www.mcserversoft.com/). Afaik it's implemented in C#. (Here's the bStats page: https://bstats.org/plugin/other/MCServerSoft/2228)

You would need to write your own Metrics class that sends data via REST. If you are interested, just tell me your account name and the name of the "plugin" and I will register it for you.

If it's really just a server implementation, there's also a special category for that. It's used by Paper and some other smaller implementations. Just like the "Other" category, you would need to write your own Metrics class, but if it's written in Java you can use Paper's implementation as a reference.

**Comment by LOOHP** [comment]
The program I'm referring to is called **[Limbo](https://www.spigotmc.org/resources/limbo-standalone-server-lightweight-solution-for-afk-or-waiting-rooms-in-your-server-network.82468/)**
It's a standalone server program that handles clients by sending them into an empty "server" that is meant to be used behind a proxy, like bungeecord.

My account name is **LOOHP**

**Comment by LOOHP** [comment]
Any update on this?

**Comment by Bastian** [comment]
Sorry and thanks for reminding me.
Your program sounds like it would fit best into the "Server Implementation" category (and not the mentioned "Other" category).
However, I've added both to your account. Feel free to experiment with both.

Take a look at https://github.com/PaperMC/Paper/issues/646#issuecomment-293876337 for more information about the "Server Implementation" category. You basically have to write your own Metrics class in C# that sends a REST POST every 30 minutes.

**Comment by LOOHP** [comment]
Thanks mate!
