### ISSUE TITLE
Can you deny specific metrics from specific versions?

### ISSUE THREAD

**Issue by Andre601** [Bastian/bStats-Metrics#81]
Because of an older version are the metrics of my plugin completely messed up (see #80 for full context) and I now would like to deny those metrics from being displayed/rendered in some way, so that the metrics are fixed.
Is there a way to reset the metrics and make bstats not render/handle metrics from specific older versions?

**Comment by Bastian** [comment]
Unfortunately that's not possible.
In your case, I would just recommend to delete the chart and create a new one with a different id.

**Comment by Andre601** [comment]
> In your case, I would just recommend to delete the chart and create a new one with a different id.

Would this cause any errors in the server/proxy console when the metrics are submitted?

**Comment by Bastian** [comment]
No, the data will just be ignored by the backend.

**Comment by Andre601** [comment]
Okay thanks for this info.

And while you're here would I like to ask a (hopefully easy to answer) question:
You may already know that I have a project that is split into three separate modules: Core, Velocity and BungeeCord.

I now use bstats-base in the Code module to have a `getPie()` method which returns a new DrilldownPie instance.
My question now is, should I relocate this base library or leave it as is? I'm not sure if relocating it would cause unwanted issues when compiling the plugin instances...

**Comment by Andre601** [comment]
See https://github.com/Bastian/bStats-Metrics/issues/82#issuecomment-798879746 for why it isn't that simple.

I can't and won't have multiple BStats dependencies in my core as it would only make it bloated without reason, once I build the jar files.
And I do use `org.bstats` as pattern, so don't worry about this.

You can see my current setup of everything here, to get yourself a picture of my situation: https://github.com/Andre601/OneVersionRemake/tree/feature/move-drilldownpie-method
