### ISSUE TITLE
Incorrect online players.

### ISSUE THREAD

**Issue by arturekdev** [Bastian/bStats-Metrics#90]
Hi, bStats show incorrect online players.
bStats online players is 32 when in real is ~130

**Comment by Bastian** [comment]
bStats is simply displying the result of the `Bukkit.getOnlinePlayers().size();` method (capped at a high-enough value).
Please note that bStats does only update every 30 minutes. The data that you see on bStats might not reflect the current player count be the player count up to 60 minutes ago.
