### ISSUE TITLE
Taiwan is a part of China

### ISSUE THREAD

**Issue by heipiao233** [Bastian/bStats-Metrics#91]
![](https://user-images.githubusercontent.com/81846300/123050983-dc565c80-d433-11eb-8ebb-dc74bb7ba222.png)
![](https://user-images.githubusercontent.com/81846300/123050998-dfe9e380-d433-11eb-9575-6a13d1887568.png)

**Comment by Bastian** [comment]
We already had this discussion.
https://github.com/Bastian/bStats/issues/77
