### ISSUE TITLE
3.0.0 breaking changes

### ISSUE THREAD

**Issue by nothub** [Bastian/bStats-Metrics#99]
With the latest release, the major version was bumped, this usually indicates an incompatible and breaking api change.
I cant find any documentation of changed api, is it safe to assume version 3.0.0 is compatible with the 2.2.1 api?

**Comment by Bastian** [comment]
The breaking change only affects the Sponge Metrics classes. If you do not use Sponge, you are fine.

I'll add some more information to the [GitHub release](https://github.com/Bastian/bStats-Metrics/releases/tag/v3.0.0). :-)
